version: "3"

services:
  app:
    container_name: demo.app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - /etc/hosts:/etc/hosts
    command: >
      sh -c "python app/manage.py runserver 0.0.0.0:8000
      && python test_polls.py"
  selenium-hub:
    image: selenium/hub:3.141.59-yttrium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    container_name: demo.chrome
    image: selenium/node-chrome:3.141.59-yttrium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    container_name: demo.firefox
    image: selenium/node-firefox:3.141.59-yttrium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
